Refactor Alpine "scanelf" to use similar "ldd" to Debian to avoid new errors in 4.1.2
```
+ apk add --no-network --virtual .redmine-rundeps so:libc.musl-x86_64.so.1 so:libc.so.6 so:libdl.so.2 so:libm.so.6 so:libmariadb.so.3 so:libpq.so.5 so:libpthread.so.0 so:libsqlite3.so.0 so:libsybdb.so.5
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
ERROR: unable to select packages:
  so:libc.so.6 (no such package):
    required by: .redmine-rundeps-20210322.211811[so:libc.so.6]
  so:libdl.so.2 (no such package):
    required by: .redmine-rundeps-20210322.211811[so:libdl.so.2]
  so:libm.so.6 (no such package):
    required by: .redmine-rundeps-20210322.211811[so:libm.so.6]
  so:libpthread.so.0 (no such package):
    required by: .redmine-rundeps-20210322.211811[so:libpthread.so.0]
```